package com.winlock.parent.crypto

import java.nio.ByteBuffer
import java.nio.ByteOrder
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec
import kotlin.math.pow

/** Mirrors WinLock.Core.Offline.OfflineUnlockService.ComputeResponseCode exactly: an
 * RFC 4226-style dynamic truncation of HMAC-SHA256(secret, bigEndian(challengeId) ++
 * bigEndian(minutes)) into a 4-digit decimal code. Both sides must produce bit-identical
 * output — see CrossLanguageVectorTest, which pins this against real vectors generated by
 * the actual C# implementation, not just a by-eye port. */
object OfflineUnlockCrypto {
    // 4 digits, not 6 — same tradeoff as a debit card PIN; see the matching comment next to
    // ResponseCodeDigits in the C# OfflineUnlockService for why that's an acceptable one.
    private const val ResponseCodeDigits = 4

    fun computeResponseCode(secret: ByteArray, challengeId: Long, minutes: Int): String {
        val input = ByteBuffer.allocate(8 + 4).order(ByteOrder.BIG_ENDIAN)
        input.putLong(challengeId)
        input.putInt(minutes)

        val mac = Mac.getInstance("HmacSHA256")
        mac.init(SecretKeySpec(secret, "HmacSHA256"))
        val hash = mac.doFinal(input.array())

        return truncateToDigits(hash, ResponseCodeDigits)
    }

    private fun truncateToDigits(hmac: ByteArray, digits: Int): String {
        val offset = hmac[hmac.size - 1].toInt() and 0x0F
        val binCode = ((hmac[offset].toInt() and 0x7f) shl 24) or
            ((hmac[offset + 1].toInt() and 0xff) shl 16) or
            ((hmac[offset + 2].toInt() and 0xff) shl 8) or
            (hmac[offset + 3].toInt() and 0xff)
        val mod = 10.0.pow(digits).toInt()
        return (binCode % mod).toString().padStart(digits, '0')
    }
}
