package com.winlock.parent.crypto

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * These expected values are NOT hand-computed — they were generated by running the actual
 * WinLock.Core C# implementation (OfflineUnlockService.ComputeResponseCode,
 * ControllerAuthenticator.ComputeAuthResponse) against these exact inputs. If this test ever
 * fails after touching the crypto code, the Kotlin and C# sides have diverged and offline
 * unlock / WebSocket auth will silently produce wrong codes against a real PC.
 */
class CrossLanguageVectorTest {
    // 32 bytes: 0x00, 0x01, 0x02, ... 0x1f
    private val secret = ByteArray(32) { it.toByte() }

    @Test
    fun offlineUnlockCode_challenge42_minutes30_matchesCSharp() {
        val code = OfflineUnlockCrypto.computeResponseCode(secret, challengeId = 42, minutes = 30)
        assertEquals("8178", code)
    }

    @Test
    fun offlineUnlockCode_challenge1000000_minutes15_matchesCSharp() {
        val code = OfflineUnlockCrypto.computeResponseCode(secret, challengeId = 1_000_000, minutes = 15)
        assertEquals("1114", code)
    }

    @Test
    fun authResponse_matchesCSharp() {
        val response = ControllerAuthenticator.computeAuthResponse(secret, "test-nonce-123")
        assertEquals("AMei1JIuBXXAV4Mkt4FfcuuAtx1xBjLGRI0GCQw917o=", response)
    }
}
